spring:
  application: #配置应用名称
    name:
      library_management

  servlet: #配置文件上传，如果不配置，则默认使用Tomcat的临时目录
    multipart: #配置文件上传
      enabled: true #允许上传文件 ，SpringBoot默认值为false
      max-file-size: 10MB #文件最大10MB
      max-request-size: 10MB #请求最大10MB
  #配置数据库的连接信息
  datasource:
    url: jdbc:mysql://localhost:3306/book_management?serverTimezone=UTC&useSSL=false
    #url: jdbc:mysql://mysql:3306/book_management?serverTimezone=UTC&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456

#MyBatis配置
mybatis:
  #配置MyBatis的包扫描
  type-handlers-package: org.fly.common.exception
  configuration:
    # 配置MyBatis日志输出把查询情况到控制台
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 配置数据库字段与实体类属性的映射关系,符合驼峰命名规则时，数据会自动封装
    map-underscore-to-camel-case: true



#配置事务管理日志级别
logging:
  level:
    org.springframework.jdbc.support.JdbcTransactionManager: debug
#定时任务配置
schedule:
  log-cleanup:
    cron: "0 00 4 * * ?"  # "0 00 2 * * ?" 对应 “秒 分 时 日 月 星期 ”
    retention-days: 90     # 保留90天

#配置文件上传相对路径-本地存储
#upload:
#  path: E:/develop/idea/workspace/fly_personal_develop/library_web_management/coverImage/

#阿里云oss
aliyun:
  oss:
    endpoint: https://oss-cn-beijing.aliyuncs.com
    bucketName: library-web-fly
    region: cn-beijing



